{
 "title": "ETH2 Sync Data",
 "description": "Beacon Chain Syncing Dashboards",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Epoch Sync Progress",
   "type": "gauge",
   "description": "Beacon chain sync process",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(beacon_finalized_epoch / beacon_current_epoch) * 100"
    }
   ]
  },
  {
   "title": "Time Left to Sync",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "h" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "((beacon_current_epoch - beacon_finalized_epoch) / rate(beacon_finalized_epoch[$__rate_interval])) / 3600"
    }
   ]
  },
  {
   "title": "Epochs Synced/Minute",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "increase(beacon_finalized_epoch[1m])"
    }
   ]
  },
  {
   "title": "Current Epoch",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "beacon_current_epoch" }
   ]
  },
  {
   "title": "Last Synced Epoch",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 5, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "beacon_finalized_epoch" }
   ]
  },
  {
   "title": "Peers",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 10, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "nbc_peers" }
   ]
  },
  {
   "title": "Resources",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{instance=\"localhost:8008\"}[$__rate_interval]) * 100",
     "legendFormat": "CPU usage %"
    },
    {
     "expr": "process_open_fds{instance=\"localhost:8008\"}",
     "legendFormat": "open file descriptors"
    },
    {
     "expr": "process_resident_memory_bytes{instance=\"localhost:8008\"}",
     "legendFormat": "RSS"
    },
    {
     "expr": "nim_gc_mem_bytes{instance=\"localhost:8008\"}",
     "legendFormat": "Nim GC mem total"
    },
    {
     "expr": "nim_gc_mem_occupied_bytes{instance=\"localhost:8008\"}",
     "legendFormat": "Nim GC mem used"
    }
   ]
  }
 ]
}